### ISSUE TITLE
current `reqwest` version `0.9` does not use automatic proxy detection

### ISSUE THREAD

**Issue by dlaehnemann** [ksk001100/ruget#13]
I have an issue where I am behind a proxy that is properly configured (with `HTTPS_PROXY` and `HTTP_PROXY` set), but `ruget` doesn't detect this proxy setting. Just as a quick test-case (when you are behind a proxy), the [installation process of `plotly_kaleido` serves well](https://github.com/igiagkiozis/plotly/blob/8903ff03ce9e8183624c40ccf7ddf863799cb92e/plotly_kaleido/build.rs#L112-L120). A regular `wget` works with the `HTTPS_PROXY` setting:

```
wget https://github.com/plotly/Kaleido/releases/download/v0.2.1/kaleido_linux_x64.zip
```

The respective `ruget` command run in the installation process is:
```
ruget -o kaleido.zip https://github.com/plotly/Kaleido/releases/download/v0.2.1/kaleido_linux_x64.zip
```

And it throws:
```
thread 'main' panicked at 'head failed...: Error(Hyper(Error(Connect, Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" })), "https://github.com/plotly/Kaleido/releases/download/v0.2.1/kaleido_linux_x64.zip")', /path/to/.cargo/registry/src/github.com-1ecc6299db9ec823/ruget-0.4.3/src/lib/utils.rs:9:39
```

The [`reqwest` `CHANGELOG.md` suggests that auto-detection of system proxies was introduced in `v0.10.0`](https://github.com/seanmonstar/reqwest/blob/eeca649a3d70c353043b2e42684c6d74f4ba5cae/CHANGELOG.md#v0100).

Thus, my suggested fix would be to update the `reqwest` version that `ruget` depends on to at least `0.10.`, but maybe even the latest `0.11` while going through (potentially breaking) changes in `reqwest`.

**Comment by dlaehnemann** [comment]
That was quick, and looks reasonably painless. Many thanks, @ksk001100, also for the immediate new release!

**Comment by ksk001100** [comment]
@dlaehnemann 
Thank you for the issue report!
