### ISSUE TITLE
Compilation fails "no method named `usage` found for struct `Flag` in the current scope"

### ISSUE THREAD

**Issue by Scipi** [ksk001100/ruget#6]
Hello,

I'm on rustc `1.48.0`, cargo `1.48.0`, and ruget `0.4.2`

When running `cargo install ruget` I'm getting a compilation error:

```
error[E0599]: no method named `usage` found for struct `Flag` in the current scope
  --> /home/scipi/.cargo/registry/src/github.com-1ecc6299db9ec823/ruget-0.4.2/src/main.rs:56:14
   |
56 |             .usage("--output, -o: ruget [url] --output [file name]")
   |              ^^^^^ method not found in `Flag`

```

Poking around a little, it looks like seahorse::Flag changed `.usage()` to `.description()` and this project was never updated. This is breaking a couple downstream projects that depend on this tool (namely https://github.com/igiagkiozis/plotly)

**Comment by Scipi** [comment]
~~Looking further into this, I'm unsure of why this issue is even arising. `Cargo.toml` for this project specifies `seahorse = "1.0.0"`, which has `.usage()`, but for some reason my cargo insists on using `seahorse = "1.1.1"` which contains the breaking api change.~~

Edit: Looks like I found the reason. Cargo implicitly treats `seahorse = "1.0.0"` as `seahorse = "^1.0.0"` so it fetches the `1.1.1` version. A quick fix would be to specify the dependency as locked to `1.0.0` with `seahorse = "=1.0.0"`

**Comment by ksk001100** [comment]
@Scipi 
Thanks for reporting the issue!

I will make a fix to upgrade the version to 1.1 immediately.

**Comment by ksk001100** [comment]
Upgrade seahorse and close the issue as the build was successful

**Comment by Scipi** [comment]
Awesome, thank you c:
